// Eleven v3 supported languages; verified against ElevenLabs documentation.
const GITA_LANGUAGES = {
  "en": "English",
  "hi": "Hindi · हिन्दी",
  "as": "Assamese · অসমীয়া",
  "bn": "Bengali · বাংলা",
  "gu": "Gujarati · ગુજરાતી",
  "kn": "Kannada · ಕನ್ನಡ",
  "ml": "Malayalam · മലയാളം",
  "mr": "Marathi · मराठी",
  "ne": "Nepali · नेपाली",
  "pa": "Punjabi · ਪੰਜਾਬੀ",
  "sd": "Sindhi · سنڌي",
  "ta": "Tamil · தமிழ்",
  "te": "Telugu · తెలుగు",
  "ur": "Urdu · اردو",
  "af": "Afrikaans",
  "ar": "Arabic",
  "hy": "Armenian",
  "az": "Azerbaijani",
  "be": "Belarusian",
  "bs": "Bosnian",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "ceb": "Cebuano",
  "ny": "Chichewa",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "nl": "Dutch",
  "et": "Estonian",
  "fil": "Filipino",
  "fi": "Finnish",
  "fr": "French",
  "gl": "Galician",
  "ka": "Georgian",
  "de": "German",
  "el": "Greek",
  "ha": "Hausa",
  "he": "Hebrew",
  "hu": "Hungarian",
  "is": "Icelandic",
  "id": "Indonesian",
  "ga": "Irish",
  "it": "Italian",
  "ja": "Japanese",
  "jv": "Javanese",
  "kk": "Kazakh",
  "ky": "Kirghiz",
  "ko": "Korean",
  "lv": "Latvian",
  "ln": "Lingala",
  "lt": "Lithuanian",
  "lb": "Luxembourgish",
  "mk": "Macedonian",
  "ms": "Malay",
  "zh": "Mandarin Chinese",
  "no": "Norwegian",
  "ps": "Pashto",
  "fa": "Persian",
  "pl": "Polish",
  "pt": "Portuguese",
  "ro": "Romanian",
  "ru": "Russian",
  "sr": "Serbian",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "es": "Spanish",
  "sw": "Swahili",
  "sv": "Swedish",
  "th": "Thai",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "vi": "Vietnamese",
  "cy": "Welsh"
};
