const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
const catalog=fs.readFileSync('languages.js','utf8');
const shared=stripTypeScriptTypes(fs.readFileSync('supabase/functions/_shared/languages.ts','utf8').replace('export ',''));
const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/tts-krishna/index.ts','utf8').replace(/^import .*;\n/gm,''));
function runtime(paid=true){const calls=[];let handler;const c=vm.createContext({Response,AbortSignal,console:{error(){}},fetch:async(url,options)=>{const body=JSON.parse(options.body);calls.push({url,body});return url.includes('googleapis')?new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({text:'अनुवादित अर्थ'})}]}}]})):new Response('mp3',{headers:{'Content-Type':'audio/mpeg'}});},Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn},createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'u'}}})},from:()=>({select:()=>({eq:()=>({single:async()=>({data:{plan_status:'annual',payment_status:paid?'paid':'pending',access_expires_at:'2099-01-01'}})})})})})});vm.runInContext(shared+source,c);return {calls,request:body=>handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer user','Content-Type':'application/json'},body:JSON.stringify(body)}))};}
test('all 74 languages shared by UI and backend',()=>{const a=vm.runInNewContext(catalog+'JSON.stringify(GITA_LANGUAGES)'),b=vm.runInNewContext(shared+'JSON.stringify(GITA_LANGUAGES)');assert.equal(a,b);assert.equal(Object.keys(JSON.parse(a)).length,74);});
test('translation is returned as text without charging for speech',async()=>{const {request,calls}=runtime();const r=await request({operation:'translate',text:'Your duty',language:'hi'});assert.equal(r.status,200);assert.equal((await r.json()).text,'अनुवादित अर्थ');assert.equal(calls.length,1);assert.match(calls[0].body.systemInstruction.parts[0].text,/Hindi/);});
test('all offered languages route meaning audio to v3 without retranslation',async()=>{const languages=JSON.parse(vm.runInNewContext(catalog+'JSON.stringify(GITA_LANGUAGES)'));for(const language of Object.keys(languages)){const {request,calls}=runtime();assert.equal((await request({text:'Localized meaning',language,translated:true})).status,200);assert.equal(calls.length,1);assert.equal(calls[0].body.model_id,'eleven_v3');assert.equal(calls[0].body.text,'Localized meaning');}});
test('Sanskrit verse text remains unchanged by language selection',async()=>{const {request,calls}=runtime();await request({text:'धर्मक्षेत्रे कुरुक्षेत्रे ॥ १.१ ॥',kind:'verse',language:'fr'});assert.equal(calls.length,1);assert.equal(calls[0].body.text,'धर्मक्षेत्रे कुरुक्षेत्रे');assert.equal(calls[0].body.model_id,'eleven_multilingual_v2');});
test('unsupported languages and unpaid access rejected before provider use',async()=>{let r=runtime();assert.equal((await r.request({text:'hello',language:'invalid'})).status,400);assert.equal(r.calls.length,0);r=runtime(false);assert.equal((await r.request({operation:'translate',text:'hello',language:'hi'})).status,403);assert.equal(r.calls.length,0);});
test('chat target language is a system instruction',async()=>{let body;const s=stripTypeScriptTypes(fs.readFileSync('supabase/functions/ask-krishna/index.ts','utf8').replace(/^import .*;\n/gm,''));const c=vm.createContext({AbortSignal,Deno:{serve(){}},fetch:async(u,o)=>{body=JSON.parse(o.body);return {};}});vm.runInContext(shared+s,c);await c.geminiRequest('key',[],4096,true,'ta');assert.match(body.systemInstruction.parts[0].text,/RESPONSE LANGUAGE: Tamil/);assert.match(body.systemInstruction.parts[0].text,/Keep references in exactly BG/);});
const frontend=fs.readFileSync('app.js','utf8');
test('late translation cannot replace newly selected language',async()=>{let resolves=[];const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);};const c=vm.createContext({$,document:{querySelectorAll:()=>[]},stopSpeech(){},cleanTranslation:s=>s,selectedVerse:{translation_english:'Act'},currentTab:'meaning',authSession:{access_token:'token'},authHeaders:()=>({}),SUPA:'',fetch:()=>new Promise(resolve=>resolves.push(resolve))});vm.runInContext(frontend.slice(frontend.indexOf("let chatLanguage='en'"),frontend.indexOf('function stepVerse')),c);vm.runInContext("renderTab('meaning')",c);vm.runInContext("meaningLanguage='ta';renderTab('meaning')",c);resolves[1]({ok:true,json:async()=>({text:'Tamil meaning'})});await vm.runInContext('meaningReady',c);resolves[0]({ok:true,json:async()=>({text:'Old Hindi meaning'})});await new Promise(setImmediate);assert.equal($('detailMeaning').textContent,'Tamil meaning');});
test('cancelled narration cannot play an old generated clip',async()=>{let resolve,played=false;const c=vm.createContext({narrationGeneration:1,fetchTTS:()=>new Promise(r=>resolve=r),playBlob:async()=>{played=true;}});vm.runInContext(frontend.slice(frontend.indexOf('async function playText('),frontend.indexOf('async function listenReply(')),c);const pending=c.playText('Meaning','hi',1);c.narrationGeneration=2;resolve({});await pending;assert.equal(played,false);});
