const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{stripTypeScriptTypes}=require('node:module'),{webcrypto,createHmac}=require('node:crypto');
const source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/razorpay-webhook/index.ts','utf8').replace(/^import .*;\n/gm,''));
function handler(error=null,logFails=false){let serve,calls=0;const logged=[];const c=vm.createContext({Response,TextEncoder,crypto:webcrypto,ANNUAL_PRICE_PAISE:100000,serviceKey:()=> 'mock',console:{error(){}},Deno:{env:{get:key=>key==='RAZORPAY_WEBHOOK_SECRET'?'test-secret':'mock'},serve:fn=>serve=fn},createClient:()=>({from:table=>({insert:async row=>{assert.equal(table,'payment_events');if(logFails)throw new Error('log down');logged.push(row);return {error:null};}}),rpc:async(name,args)=>{calls++;assert.equal(name,'apply_annual_payment');assert.equal(args.p_payment_id,'payment');return {data:{unlocked:'test-user'},error};}})});vm.runInContext(source,c);return {request:signature=>serve(new Request('https://test',{method:'POST',headers:{'x-razorpay-signature':signature},body:raw})),requestBody:(body,sig)=>serve(new Request('https://test',{method:'POST',headers:{'x-razorpay-signature':sig},body})),get calls(){return calls},logged};}
const raw=JSON.stringify({event:'payment_link.paid',payload:{payment_link:{entity:{id:'link',status:'paid',notes:{user_id:'test-user'}}},payment:{entity:{id:'payment',status:'captured',amount:100000,currency:'INR'}}}}),signature=createHmac('sha256','test-secret').update(raw).digest('hex');
test('verified payment uses exactly one database transaction',async()=>{const h=handler();assert.equal((await h.request(signature)).status,200);assert.equal(h.calls,1);});
test('database failure stays retryable for payment provider',async()=>{const h=handler({message:'database unavailable'});assert.equal((await h.request(signature)).status,500);});
test('invalid webhook signature cannot apply a payment',async()=>{const h=handler();assert.equal((await h.request('invalid')).status,401);assert.equal(h.calls,0);});
const failedRaw=JSON.stringify({event:'payment.failed',payload:{payment:{entity:{id:'pay_f',order_id:'order_1',status:'failed',method:'upi',amount:100000,contact:'+919876543210',vpa:'someone@okbank',error_code:'BAD_REQUEST_ERROR',error_description:'Payment was unsuccessful as you could not complete it in time.',error_source:'customer',error_step:'payment_authentication',error_reason:'payment_timed_out',notes:{user_id:'test-user'}}}}}),failedSig=createHmac('sha256','test-secret').update(failedRaw).digest('hex');
test('failed payment attempt is recorded with its reason and no payment details',async()=>{const h=handler();const res=await h.requestBody(failedRaw,failedSig);assert.equal(res.status,200);assert.equal(h.calls,0);assert.equal(h.logged.length,1);const row=h.logged[0];assert.equal(row.event,'payment.failed');assert.equal(row.order_id,'order_1');assert.equal(row.error_reason,'payment_timed_out');assert.equal(row.method,'upi');assert.equal(row.contact_last4,'3210');assert.equal(row.user_id,'test-user');assert.ok(!JSON.stringify(row).includes('someone@okbank'));assert.ok(!JSON.stringify(row).includes('9876543210'));});
test('paid event is recorded and still unlocks access',async()=>{const h=handler();assert.equal((await h.request(signature)).status,200);assert.equal(h.calls,1);assert.equal(h.logged[0].event,'payment_link.paid');});
test('event logging failure never blocks a payment',async()=>{const h=handler(null,true);assert.equal((await h.request(signature)).status,200);assert.equal(h.calls,1);});
test('unsigned events are not recorded',async()=>{const h=handler();assert.equal((await h.request('invalid')).status,401);assert.equal(h.logged.length,0);});
