-- Accounts and payments. These objects were created in the SQL editor, not
-- through a migration; this file reconstructs them from the live database so
-- the schema can be rebuilt from the repo. It is idempotent, so running it
-- against the existing project changes nothing. Columns added later
-- (access_expires_at, signup_*, free_questions_used) come from their own
-- migrations.

create schema if not exists private;

create table if not exists public.user_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  plan_status text not null default 'free',
  payment_provider text,
  payment_id text,
  payment_link_id text,
  amount_paid_paise integer check (amount_paid_paise is null or amount_paid_paise >= 0),
  purchased_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid', 'refunded', 'failed')),
  phone text,
  auth_provider text
);
alter table public.user_accounts enable row level security;
-- Originally allowed 'lifetime'; 20260927121436 narrows it to free/annual.
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'user_accounts_plan_status_check') then
    alter table public.user_accounts add constraint user_accounts_plan_status_check
      check (plan_status in ('free', 'lifetime', 'annual'));
  end if;
end $$;

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'razorpay',
  payment_link_id text,
  payment_id text unique,
  amount_paise integer not null,
  currency text not null default 'INR',
  status text not null default 'created',
  raw_event jsonb,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);
alter table public.payment_transactions enable row level security;
create index if not exists payment_transactions_user_id_idx on public.payment_transactions (user_id);
create unique index if not exists payment_transactions_link_id_uidx
  on public.payment_transactions (payment_link_id) where payment_link_id is not null;

-- Users may read their own account and payments; only the server writes.
drop policy if exists users_read_own_account on public.user_accounts;
create policy users_read_own_account on public.user_accounts
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists users_read_own_transactions on public.payment_transactions;
create policy users_read_own_transactions on public.payment_transactions
  for select to authenticated using ((select auth.uid()) = user_id);
revoke insert, update, delete on public.user_accounts, public.payment_transactions from anon, authenticated;

-- Legacy "lifetime" read policies. Nothing matches them since the switch to
-- annual access (20260927121436); content is readable through the
-- public_read_* policies.
drop policy if exists lifetime_read_chapters on public.gita_chapters;
create policy lifetime_read_chapters on public.gita_chapters for select to authenticated
  using (exists (select 1 from public.user_accounts ua where ua.user_id = (select auth.uid()) and ua.plan_status = 'lifetime' and ua.payment_status = 'paid'));
drop policy if exists lifetime_read_verses on public.gita_verses;
create policy lifetime_read_verses on public.gita_verses for select to authenticated
  using (exists (select 1 from public.user_accounts ua where ua.user_id = (select auth.uid()) and ua.plan_status = 'lifetime' and ua.payment_status = 'paid'));
drop policy if exists lifetime_read_topics on public.verse_topics;
create policy lifetime_read_topics on public.verse_topics for select to authenticated
  using (exists (select 1 from public.user_accounts ua where ua.user_id = (select auth.uid()) and ua.plan_status = 'lifetime' and ua.payment_status = 'paid'));

-- Every new auth user gets an account row (phone sign-ups have no email).
create or replace function private.handle_new_user_account()
returns trigger
language plpgsql security definer
set search_path to 'public', 'auth', 'pg_temp'
as $function$
begin
  insert into public.user_accounts (
    user_id,email,phone,auth_provider
  )
  values (
    new.id,
    coalesce(new.email,''),
    new.phone,
    coalesce(new.raw_app_meta_data->>'provider','unknown')
  )
  on conflict (user_id) do update
  set
    email = excluded.email,
    phone = coalesce(excluded.phone, public.user_accounts.phone),
    auth_provider = coalesce(excluded.auth_provider, public.user_accounts.auth_provider),
    updated_at = now();
  return new;
end;
$function$;

drop trigger if exists on_auth_user_created_account on auth.users;
create trigger on_auth_user_created_account after insert on auth.users
  for each row execute function private.handle_new_user_account();

create or replace function private.touch_user_accounts_updated_at()
returns trigger
language plpgsql
set search_path to 'public', 'pg_temp'
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

drop trigger if exists user_accounts_updated_at on public.user_accounts;
create trigger user_accounts_updated_at before update on public.user_accounts
  for each row execute function private.touch_user_accounts_updated_at();
